#####Storage-Class#########
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: do-block-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4

#### PV  ######
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-pv
  labels:
    type: efk-pv
  
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
#### PVC #####
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data
  namespace: logging
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
